// UI 확인용 초기 데이터
// export const initialState = [
//     {
//         id: 14,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "white",
//         top: 550,
//         left: 1370,
//         pageCount: 1,
//     },
//     {
//         id: 9,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "white",
//         top: 100,
//         left: 850,
//         pageCount: 1,
//     },
//     {
//         id: 12,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "orange",
//         top: 644,
//         left: 1810,
//         pageCount: 1,
//     },
//     {
//         id: 11,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "orange",
//         top: 1168,
//         left: 1264,
//         pageCount: 1,
//     },
//     {
//         id: 15,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "white",
//         top: 1154,
//         left: 1676,
//         pageCount: 1,
//     },
//     {
//         id: 10,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "white",
//         top: 38,
//         left: 1346,
//         pageCount: 1,
//     },
//     {
//         id: 7,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "orange",
//         top: 1144,
//         left: 410,
//         pageCount: 1,
//     },
//     {
//         id: 16,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "orange",
//         top: 0,
//         left: 2164,
//         pageCount: 1,
//     },
//     {
//         id: 8,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "orange",
//         top: 564,
//         left: 930,
//         pageCount: 1,
//     },
//     {
//         id: 13,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "white",
//         top: 100,
//         left: 1758,
//         pageCount: 1,
//     },
//     {
//         id: 4,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "orange",
//         top: 24,
//         left: 428,
//         pageCount: 1,
//     },
//     {
//         id: 18,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "white",
//         top: 1170,
//         left: 2642,
//         pageCount: 1,
//     },
//     {
//         id: 21,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "white",
//         top: 580,
//         left: 2220,
//         pageCount: 1,
//     },
//     {
//         id: 19,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "orange",
//         top: 672,
//         left: 2762,
//         pageCount: 1,
//     },
//     {
//         id: 20,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "white",
//         top: 150,
//         left: 2610,
//         pageCount: 1,
//     },
//     {
//         id: 3,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "orange",
//         top: 612,
//         left: 0,
//         pageCount: 1,
//     },
//     {
//         id: 22,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "orange",
//         top: 0,
//         left: 3176,
//         pageCount: 1,
//     },
//     {
//         id: 6,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "white",
//         top: 626,
//         left: 508,
//         pageCount: 1,
//     },
//     {
//         id: 5,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "white",
//         top: 1084,
//         left: 850,
//         pageCount: 1,
//     },
//     {
//         id: 17,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "orange",
//         top: 1136,
//         left: 2222,
//         pageCount: 1,
//     },
//     {
//         id: 24,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "white",
//         top: 606,
//         left: 3176,
//         pageCount: 1,
//     },
//     {
//         id: 1,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "white",
//         top: 90,
//         left: 20,
//         pageCount: 1,
//     },
//     {
//         id: 23,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "orange",
//         top: 1168,
//         left: 3146,
//         pageCount: 1,
//     },
//     {
//         id: 2,
//         content: "한여름 밤, 별들이 빛나는 밤하늘을 바라보며 시간을 잊어버리곤 합니다. 그 유쾌한 풍경과 함께 친구들과 웃음으로 가득한 순간들이 쌓이며 행복한 기억이 된답니다.",
//         name: "닉네임",
//         type: "white",
//         top: 1150,
//         left: 5,
//         pageCount: 1,
//     },
// ];

// 실사용 초기 데이터
export const initialState = [
    {
        id: 14,
        content: "",
        name: "",
        type: "white",
        top: 550,
        left: 1370,
    },
    {
        id: 9,
        content: "",
        name: "",
        type: "white",
        top: 100,
        left: 850,
    },
    {
        id: 12,
        content: "",
        name: "",
        type: "orange",
        top: 644,
        left: 1810,
    },
    {
        id: 11,
        content: "",
        name: "",
        type: "orange",
        top: 1168,
        left: 1264,
    },
    {
        id: 15,
        content: "",
        name: "",
        type: "white",
        top: 1154,
        left: 1676,
    },
    {
        id: 10,
        content: "",
        name: "",
        type: "white",
        top: 38,
        left: 1346,
    },
    {
        id: 7,
        content: "",
        name: "",
        type: "orange",
        top: 1144,
        left: 410,
    },
    {
        id: 16,
        content: "",
        name: "",
        type: "orange",
        top: 0,
        left: 2164,
    },
    {
        id: 8,
        content: "",
        name: "",
        type: "orange",
        top: 564,
        left: 930,
    },
    {
        id: 13,
        content: "",
        name: "",
        type: "white",
        top: 100,
        left: 1758,
    },
    {
        id: 4,
        content: "",
        name: "",
        type: "orange",
        top: 24,
        left: 428,
    },
    {
        id: 18,
        content: "",
        name: "",
        type: "white",
        top: 1170,
        left: 2642,
    },
    {
        id: 21,
        content: "",
        name: "",
        type: "white",
        top: 580,
        left: 2220,
    },
    {
        id: 19,
        content: "",
        name: "",
        type: "orange",
        top: 672,
        left: 2762,
    },
    {
        id: 20,
        content: "",
        name: "",
        type: "white",
        top: 150,
        left: 2610,
    },
    {
        id: 3,
        content: "",
        name: "",
        type: "orange",
        top: 612,
        left: 0,
    },
    {
        id: 22,
        content: "",
        name: "",
        type: "orange",
        top: 0,
        left: 3176,
    },
    {
        id: 6,
        content: "",
        name: "",
        type: "white",
        top: 626,
        left: 508,
    },
    {
        id: 5,
        content: "",
        name: "",
        type: "white",
        top: 1084,
        left: 850,
    },
    {
        id: 17,
        content: "",
        name: "",
        type: "orange",
        top: 1136,
        left: 2222,
    },
    {
        id: 24,
        content: "",
        name: "",
        type: "white",
        top: 606,
        left: 3176,
    },
    {
        id: 1,
        content: "",
        name: "",
        type: "white",
        top: 90,
        left: 20,
    },
    {
        id: 23,
        content: "",
        name: "",
        type: "orange",
        top: 1168,
        left: 3146,
    },
    {
        id: 2,
        content: "",
        name: "",
        type: "white",
        top: 1150,
        left: 5,
    },
    // 둘째장
    {
        id: 38,
        content: "",
        name: "",
        type: "white",
        top: 550,
        left: 1370,
    },
    {
        id: 33,
        content: "",
        name: "",
        type: "white",
        top: 100,
        left: 850,
    },
    {
        id: 36,
        content: "",
        name: "",
        type: "orange",
        top: 644,
        left: 1810,
    },
    {
        id: 35,
        content: "",
        name: "",
        type: "orange",
        top: 1168,
        left: 1264,
    },
    {
        id: 39,
        content: "",
        name: "",
        type: "white",
        top: 1154,
        left: 1676,
    },
    {
        id: 34,
        content: "",
        name: "",
        type: "white",
        top: 38,
        left: 1346,
    },
    {
        id: 31,
        content: "",
        name: "",
        type: "orange",
        top: 1144,
        left: 410,
    },
    {
        id: 40,
        content: "",
        name: "",
        type: "orange",
        top: 0,
        left: 2164,
    },
    {
        id: 32,
        content: "",
        name: "",
        type: "orange",
        top: 564,
        left: 930,
    },
    {
        id: 37,
        content: "",
        name: "",
        type: "white",
        top: 100,
        left: 1758,
    },
    {
        id: 28,
        content: "",
        name: "",
        type: "orange",
        top: 24,
        left: 428,
    },
    {
        id: 42,
        content: "",
        name: "",
        type: "white",
        top: 1170,
        left: 2642,
    },
    {
        id: 45,
        content: "",
        name: "",
        type: "white",
        top: 580,
        left: 2220,
    },
    {
        id: 43,
        content: "",
        name: "",
        type: "orange",
        top: 672,
        left: 2762,
    },
    {
        id: 44,
        content: "",
        name: "",
        type: "white",
        top: 150,
        left: 2610,
    },
    {
        id: 27,
        content: "",
        name: "",
        type: "orange",
        top: 612,
        left: 0,
    },
    {
        id: 46,
        content: "",
        name: "",
        type: "orange",
        top: 0,
        left: 3176,
    },
    {
        id: 30,
        content: "",
        name: "",
        type: "white",
        top: 626,
        left: 508,
    },
    {
        id: 29,
        content: "",
        name: "",
        type: "white",
        top: 1084,
        left: 850,
    },
    {
        id: 41,
        content: "",
        name: "",
        type: "orange",
        top: 1136,
        left: 2222,
    },
    {
        id: 48,
        content: "",
        name: "",
        type: "white",
        top: 606,
        left: 3176,
    },
    {
        id: 25,
        content: "",
        name: "",
        type: "white",
        top: 90,
        left: 20,
    },
    {
        id: 47,
        content: "",
        name: "",
        type: "orange",
        top: 1168,
        left: 3146,
    },
    {
        id: 26,
        content: "",
        name: "",
        type: "white",
        top: 1150,
        left: 5,
    },
    // 셋째장
    {
        id: 62,
        content: "",
        name: "",
        type: "white",
        top: 550,
        left: 1370,
    },
    {
        id: 57,
        content: "",
        name: "",
        type: "white",
        top: 100,
        left: 850,
    },
    {
        id: 60,
        content: "",
        name: "",
        type: "orange",
        top: 644,
        left: 1810,
    },
    {
        id: 59,
        content: "",
        name: "",
        type: "orange",
        top: 1168,
        left: 1264,
    },
    {
        id: 63,
        content: "",
        name: "",
        type: "white",
        top: 1154,
        left: 1676,
    },
    {
        id: 58,
        content: "",
        name: "",
        type: "white",
        top: 38,
        left: 1346,
    },
    {
        id: 55,
        content: "",
        name: "",
        type: "orange",
        top: 1144,
        left: 410,
    },
    {
        id: 64,
        content: "",
        name: "",
        type: "orange",
        top: 0,
        left: 2164,
    },
    {
        id: 56,
        content: "",
        name: "",
        type: "orange",
        top: 564,
        left: 930,
    },
    {
        id: 61,
        content: "",
        name: "",
        type: "white",
        top: 100,
        left: 1758,
    },
    {
        id: 52,
        content: "",
        name: "",
        type: "orange",
        top: 24,
        left: 428,
    },
    {
        id: 66,
        content: "",
        name: "",
        type: "white",
        top: 1170,
        left: 2642,
    },
    {
        id: 69,
        content: "",
        name: "",
        type: "white",
        top: 580,
        left: 2220,
    },
    {
        id: 67,
        content: "",
        name: "",
        type: "orange",
        top: 672,
        left: 2762,
    },
    {
        id: 68,
        content: "",
        name: "",
        type: "white",
        top: 150,
        left: 2610,
    },
    {
        id: 51,
        content: "",
        name: "",
        type: "orange",
        top: 612,
        left: 0,
    },
    {
        id: 70,
        content: "",
        name: "",
        type: "orange",
        top: 0,
        left: 3176,
    },
    {
        id: 54,
        content: "",
        name: "",
        type: "white",
        top: 626,
        left: 508,
    },
    {
        id: 53,
        content: "",
        name: "",
        type: "white",
        top: 1084,
        left: 850,
    },
    {
        id: 65,
        content: "",
        name: "",
        type: "orange",
        top: 1136,
        left: 2222,
    },
    {
        id: 72,
        content: "",
        name: "",
        type: "white",
        top: 606,
        left: 3176,
    },
    {
        id: 49,
        content: "",
        name: "",
        type: "white",
        top: 90,
        left: 20,
    },
    {
        id: 71,
        content: "",
        name: "",
        type: "orange",
        top: 1168,
        left: 3146,
    },
    {
        id: 50,
        content: "",
        name: "",
        type: "white",
        top: 1150,
        left: 5,
    },
    // 넷째장
    {
        id: 86,
        content: "",
        name: "",
        type: "white",
        top: 550,
        left: 1370,
    },
    {
        id: 81,
        content: "",
        name: "",
        type: "white",
        top: 100,
        left: 850,
    },
    {
        id: 84,
        content: "",
        name: "",
        type: "orange",
        top: 644,
        left: 1810,
    },
    {
        id: 83,
        content: "",
        name: "",
        type: "orange",
        top: 1168,
        left: 1264,
    },
    {
        id: 87,
        content: "",
        name: "",
        type: "white",
        top: 1154,
        left: 1676,
    },
    {
        id: 82,
        content: "",
        name: "",
        type: "white",
        top: 38,
        left: 1346,
    },
    {
        id: 79,
        content: "",
        name: "",
        type: "orange",
        top: 1144,
        left: 410,
    },
    {
        id: 88,
        content: "",
        name: "",
        type: "orange",
        top: 0,
        left: 2164,
    },
    {
        id: 80,
        content: "",
        name: "",
        type: "orange",
        top: 564,
        left: 930,
    },
    {
        id: 85,
        content: "",
        name: "",
        type: "white",
        top: 100,
        left: 1758,
    },
    {
        id: 76,
        content: "",
        name: "",
        type: "orange",
        top: 24,
        left: 428,
    },
    {
        id: 90,
        content: "",
        name: "",
        type: "white",
        top: 1170,
        left: 2642,
    },
    {
        id: 93,
        content: "",
        name: "",
        type: "white",
        top: 580,
        left: 2220,
    },
    {
        id: 91,
        content: "",
        name: "",
        type: "orange",
        top: 672,
        left: 2762,
    },
    {
        id: 92,
        content: "",
        name: "",
        type: "white",
        top: 150,
        left: 2610,
    },
    {
        id: 75,
        content: "",
        name: "",
        type: "orange",
        top: 612,
        left: 0,
    },
    {
        id: 94,
        content: "",
        name: "",
        type: "orange",
        top: 0,
        left: 3176,
    },
    {
        id: 78,
        content: "",
        name: "",
        type: "white",
        top: 626,
        left: 508,
    },
    {
        id: 77,
        content: "",
        name: "",
        type: "white",
        top: 1084,
        left: 850,
    },
    {
        id: 89,
        content: "",
        name: "",
        type: "orange",
        top: 1136,
        left: 2222,
    },
    {
        id: 96,
        content: "",
        name: "",
        type: "white",
        top: 606,
        left: 3176,
    },
    {
        id: 73,
        content: "",
        name: "",
        type: "white",
        top: 90,
        left: 20,
    },
    {
        id: 95,
        content: "",
        name: "",
        type: "orange",
        top: 1168,
        left: 3146,
    },
    {
        id: 74,
        content: "",
        name: "",
        type: "white",
        top: 1150,
        left: 5,
    },
];
